version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: news_test
    networks:
      - default
networks:
  default: